# Generated by Django 4.2.1 on 2023-05-21 19:08

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='file',
            field=models.FileField(upload_to=files.models.user_directory_path),
        ),
    ]
